apiVersion: v1
kind: PersistentVolume
metadata:
  name: hw2p2-pv
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw2p2-pvc
spec:
  storageClassName: ""
  volumeName: hw2p2-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: hw2p2-postgres-db
  labels:
    name: hw2p2-postgres-db
spec:
  volumes:
  - name: hw2p2-db-vol
    persistentVolumeClaim:
     claimName: hw2p2-pvc
  containers:
  - name: hw2p2-postgres-db
    image: postgres
    env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5432
        name: postgres-tport
    volumeMounts:
    - mountPath: "/var/lib/postgresql/data"
      name: hw2p2-db-vol

---

apiVersion: v1
kind: Service
metadata:
  name: hw2p2-db-service
spec:
  selector:
    name: hw2p2-postgres-db
  type: ClusterIP
  ports:
  - name: postgres-port
    protocol: TCP
    port: 5432
    targetPort: postgres-tport

---

apiVersion: v1
kind: Pod
metadata:
  name: hw2p2-todo-app
  labels:
    name: hw2p2-todo-app
spec:
  containers:
  - name: hw2p2-todo-app
    image: estar1337/hw2p2
    env:
    - name: PGHOST
      value: hw2p2-db-service
    - name: PGUSER
      value: postgres
    - name: PGDATABASE
      value: postgres
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
        name: todo-app-tport

---

apiVersion: v1
kind: Service
metadata:
  name: hw2p2-load-balancer-service
spec:
  selector:
    name: hw2p2-todo-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: todo-app-tport

